### ISSUE TITLE
Files are not sorted alphabetically in the File List (leads to deleting wrong row from list, etc)

### ISSUE THREAD

**Issue by Baccount** [micahflee/onionshare#604]
When I start a share with a large file then cancel the share and  remove the large file and add a very small file I still get the message, "warning sending large files could take hours".
1. Start a share with a file over 200 Mbs
2. when the share starts cancel it.
3. remove the large file and add a very small file, I used a 8 Kb file
4. start a share and you should get the message "Warning sending large files could take hours", even though the only file being shared is very small.
Tested with "ux-update " branch

**Comment by mig5** [comment]
Hmm, I don't reproduce this on the ux-update branch. I tried both deleting the 200MB+ file with the 'x' button next to the filename, as well as via the main 'Delete' button.

When you say 'cancel' the share, do you mean simply 'stop' sharing? Or were you testing the 'cancel' feature in the other recent PR?

Can you make one of your videos that shows the full process?

**Comment by Baccount** [comment]
@mig5 
Here is a video showing the bug.
[bug.mov 2.zip](https://github.com/micahflee/onionshare/files/1722072/bug.mov.2.zip)

**Comment by mig5** [comment]
I still don't reproduce after copying your video (adding two files at once, not one after the other).

To rule out your changes being the cause, can you clone the ux-update branch straight from Github and compile from there, and try that version?

**Comment by mig5** [comment]
I just reproduced it after naming my files similar to yours (large file beginning with IMG, smaller file beginning with Tails).

So maybe it's an alphabetical or row/sort issue. Thanks for the report

**Comment by mig5** [comment]
It is popping the wrong item from the list (when you go to the share, the file in the zip is the larger file).

And it's not unique to large files, it happens if you add 4 small files eg MANIFEST, LICENSE, CHANGELOG, BUILD, and remove the CHANGELOG (you'll lose LICENSE).

Issue seems to be that files are being added in reverse alphabetical order now, whereas they used to be sorted properly, so we have a regression of #428

**Comment by Baccount** [comment]
@mig5 it seams to work correctly, I must of not copied file_selection.py before compiling it. #606

**Comment by micahflee** [comment]
Hmm, so I think the real crux of the issue is that the `FileList` object is both inherited from `QtWidgets.QListWidget` which contains its own list, but also has an internal `self.filenames`. These two lists might end up sorted differently.

I think the less hacky way to fix this is to refactor `FileList` and completely remove `self.filenames`, and instead only rely on the items in the QListWidget.

When it's defining an item:

```python
# Create a new item
item = QtWidgets.QListWidgetItem()
item.setIcon(icon)
item.size_bytes = size_bytes
```

You'll have to add `item.filename = filename`, so you can later still have access to the filename.

**Comment by mig5** [comment]
Cool I've fixed this in a [test branch of mine](https://github.com/mig5/onionshare/tree/604_fix_file_list_widgets_and_ordering), but there remains a problem: because you are setting a QLabel widget for the item name, there is no QString to use as the 'DisplayRole', which dictates the sorting.

I can do this:

```
item.setData(QtCore.Qt.DisplayRole, basename)
```

This magically means that the list will be sorted alphabetically properly. However, it draws the basename right over the top of your item_name and item_size QLabels!

I tried hiding it with:

```
            item.brush = QtGui.QBrush(QtGui.QColor('white'))
            item.setForeground(item.brush)
```

Which works:

![file_list](https://user-images.githubusercontent.com/99173/36463102-5e1f9f1a-1713-11e8-8b19-fa536865c226.png)

except when you *select* an item (foreground goes blue), at which point you can see the white font underneath. Argh!

![file_list_selected](https://user-images.githubusercontent.com/99173/36463095-539caf38-1713-11e8-8d77-5e3537e213ca.png)

**Comment by mig5** [comment]
OK, that [test branch above](https://github.com/mig5/onionshare/tree/604_fix_file_list_widgets_and_ordering) now has got rid of the item_name QLabel widget altogether. Instead, just show the QListWidgetItem's text that it so badly wants to show.

I couldn't work out how to stretch the window to fit 'really long filenames' in this case, so I cheat by 'trimming' the display of the filename so that it's truncated with a ... at the end.

Finally, I encountered weird issues when the vertical scrollbar activates or when a slight resize of the window forces the scrollbar to itself change size/length.. in some cases (e.g 4 items) the text of the file names would suddenly disappear, unless you shrunk or further extended the size of the window. Maybe a Qt bug. I work around this by forcing the Scroll Bar to be always present - which I don't think you're gonna like, but it 'fixes' it.

Maybe you can take this and make it better..

**Comment by micahflee** [comment]
Thanks for working on this. I've been meaning to see if I could somehow hide the QListWidgetItem's text using css, if you we can figure out exactly what element to hide.

But actually, I think I like the file size on the right better than right under the filenames because it makes it so each row can fit more. And always having the scrollbar isn't ideal, but it's not too bad.

But what I don't like is that the message trimming doesn't expand to show the full filename if you make the window larger. I'm going to poke a bit at this branch and see if I can improve it.

**Comment by micahflee** [comment]
Ok I just added a commit to my own `mig5-604_fix_file_list_widgets_and_ordering` branch. It doesn't fix it yet, but maybe it's progress?

I removed filename trimming, and instead put the file size and delete button inside its own widget with a white background:

![screenshot_2018-02-22_09-55-47](https://user-images.githubusercontent.com/156128/36555419-c7ff0d28-17b6-11e8-9fd9-a5e212b29111.png)

And this does exactly what I want when resizing the window too:

![screenshot_2018-02-22_09-55-57](https://user-images.githubusercontent.com/156128/36555452-e0b33a38-17b6-11e8-8cf0-9f3ee6bdf93c.png)

However, it looks pretty weird now when you select items, and Qt's css selectors aren't nearly as robust as HTML's so I'm having trouble figuring out how to style those better:

![screenshot_2018-02-22_09-56-11](https://user-images.githubusercontent.com/156128/36555488-fef602fa-17b6-11e8-9835-4fadbbe3ce13.png)

**Comment by micahflee** [comment]
Another option is to just own the fact the item-info boxes are their own separate widgets and give them a distinct style, like this.

![screenshot_2018-02-22_10-02-18](https://user-images.githubusercontent.com/156128/36555700-9f5037b6-17b7-11e8-88ec-fbecfff86103.png)

@glenn-sorrentino do you have any thoughts on this? Basically we're having trouble making it look exactly like we want it.

**Comment by glenn-sorrentino** [comment]
I'd opt for this option: 

![36555419-c7ff0d28-17b6-11e8-9fd9-a5e212b29111](https://user-images.githubusercontent.com/28545431/36565052-23c983aa-17d4-11e8-896c-ba03c1a38e2e.png)

My thinking is that there are three states to the list items:
- Not selected
- Selected 
- Sending

By using the white background, we'd be optimizing for 2 of the 3 states:

### **Not selected**
Not an issue, and my hypothesis is that the majority of the time a user will drop files, send them, then close the app, making the list stay in this state most of the time.

### **Selected**
Another hypothesis is that OnionShare is more of an ephemeral app and isn't something that most users will have open all of the time, so curating the list will be more of an edge case.

### **Sending**
When the files are sending the user can't take any action on them, and if they can't do anything by selecting them, they probably shouldn't be selectable. If you put the list items into a disabled state when sending, it'd reduce the background color issue further.

Put another way, if you go with the border and grey background color, the user will **_always_** see a busier UI, but if you use a white background, the user will only **_sometimes_** see a busier UI. And since file sizes are so varied, there'll be a more obvious impact on the lack of uniformity in the button size, making it just a bit more distracting.
